name: Test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + Zabbix ${{ matrix.zabbix-version }}

        runs-on: ubuntu-latest

        continue-on-error: ${{ matrix.allowed-to-fail }}

        strategy:
            matrix:
                php-version:
                    - '5.6'
                    - '7.0'
                    - '7.1'
                    - '7.2'
                    - '7.3'
                allowed-to-fail: [false]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: Add PHPUnit matcher
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: "Install Composer dependencies"
              uses: "ramsey/composer-install@v1"

            - name: Run Tests
              run: composer test-cover

            - name: Publish test coverage
              run: bash <(curl -s https://codecov.io/bash) -t e4de22ca-5f85-40e5-8f90-4c633cc4df9b
